// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBy21BhpQTBe1SGjkNeH7CYG6y3xWzIeE',
    appId: '1:402987417451:web:24a5d75ad6c63c0c1a162e',
    messagingSenderId: '402987417451',
    projectId: 'mool-3bda4',
    authDomain: 'mool-3bda4.firebaseapp.com',
    storageBucket: 'mool-3bda4.appspot.com',
    measurementId: 'G-8DCCYNLZ7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCih8h7Ms0Une7BnyikDsLnA214_BZcx24',
    appId: '1:402987417451:android:2cee310cabed31781a162e',
    messagingSenderId: '402987417451',
    projectId: 'mool-3bda4',
    storageBucket: 'mool-3bda4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3YrXmqm9Lo2Xf_nkCMq3JgvhfvmwWQqs',
    appId: '1:402987417451:ios:c87fc0f7797cf2131a162e',
    messagingSenderId: '402987417451',
    projectId: 'mool-3bda4',
    storageBucket: 'mool-3bda4.appspot.com',
    iosClientId: '402987417451-caqqlqo4bot1rbleddmihar6k4157vpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3YrXmqm9Lo2Xf_nkCMq3JgvhfvmwWQqs',
    appId: '1:402987417451:ios:c87fc0f7797cf2131a162e',
    messagingSenderId: '402987417451',
    projectId: 'mool-3bda4',
    storageBucket: 'mool-3bda4.appspot.com',
    iosClientId: '402987417451-caqqlqo4bot1rbleddmihar6k4157vpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mool',
  );
}
